### ISSUE TITLE
Frozen GitHub

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1674-project-3#1]
Hi Thomas,

I'm unable to make any commits as my GitHub app is frozen. I've tried force quit, and restarted my computer, it's made no difference. I have the T.A.'s and Jed stumped as well. My website won't open in the browser (I think because of this issue), I don't even get a 404 Error, just white nothingness :( Please help! Thank you!

@thomasjbradley

**Comment by thomasjbradley** [comment]
The syncing issue I don't know without looking at it.
Come to my office hours today between 1-2 if you can.
One thought I have would be to go to GitHub > Preferences and sign out and in again.
Second thought: are there any big files in the folder? AI? PSD?

The white nothingness is caused by a validation error in your HTML: run it through the validator and fix all the problems.

**Comment by kaybow** [comment]
Hi Thomas, 

All my files are jpgs. I've already tried signing out and in. I'll come by your office, thank you.
